version: '3.9'

services:

  some-mysql:
    image: mysql:8.0
#    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3331:3306
    environment:
      MYSQL_DATABASE: Human_Friends
      MYSQL_USER: hacoc
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
#    volumes:
#      - .Human_Friends:/var/lib/mysql
#      - ./Human_Friends.sql:/docker-entrypoint-initdb.d/Human_Friends.sql
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    command:
#      - mysql -u root -p 123 GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, SHUTDOWN, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER, CREATE TABLESPACE, CREATE ROLE, DROP ROLE ON *.* TO `hacoc`@`localhost`; GRANT APPLICATION_PASSWORD_ADMIN,AUDIT_ABORT_EXEMPT,AUDIT_ADMIN,AUTHENTICATION_POLICY_ADMIN,BACKUP_ADMIN,BINLOG_ADMIN,BINLOG_ENCRYPTION_ADMIN,CLONE_ADMIN,CONNECTION_ADMIN,ENCRYPTION_KEY_ADMIN,FIREWALL_EXEMPT,FLUSH_OPTIMIZER_COSTS,FLUSH_STATUS,FLUSH_TABLES,FLUSH_USER_RESOURCES,GROUP_REPLICATION_ADMIN,GROUP_REPLICATION_STREAM,INNODB_REDO_LOG_ARCHIVE,INNODB_REDO_LOG_ENABLE,PASSWORDLESS_USER_ADMIN,PERSIST_RO_VARIABLES_ADMIN,REPLICATION_APPLIER,REPLICATION_SLAVE_ADMIN,RESOURCE_GROUP_ADMIN,RESOURCE_GROUP_USER,ROLE_ADMIN,SENSITIVE_VARIABLES_OBSERVER,SERVICE_CONNECTION_ADMIN,SESSION_VARIABLES_ADMIN,SET_USER_ID,SHOW_ROUTINE,SYSTEM_USER,SYSTEM_VARIABLES_ADMIN,TABLE_ENCRYPTION_ADMIN,TELEMETRY_LOG_ADMIN,XA_RECOVER_ADMIN ON *.* TO `hacoc`@`localhost`;
#      - docker exec -i some-mysql mysql -u hacoc -p 123 Human_Friends < Human_Friends.sql
#      - mysql -u hacoc Human_Friends -p 123 < Human_Friends.sql

#  python_app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - some-mysql
#    environment:
#      PMA_HOST: some-mysql

  myphp:
    image: phpmyadmin/phpmyadmin
    ports:
      - 333:80
    depends_on:
      - some-mysql
    environment:
      PMA_HOST: some-mysql