version: '3.9'

services:

  some-mysql:
    image: mysql:8.0
    ports:
      - 3331:3306
    environment:
      MYSQL_DATABASE: Human_Friends
      MYSQL_USER: hacoc
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    volumes:
#      - .Human_Friends.sql:/docker-entrypoint-initdb.d/Human_Friends.sql
      - .Human_Friends:/var/lib/mysql
    command:
      - mysql -u hacoc Human_Friends -p 123 < ./Human_Friends.sql

#  python_app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - some-mysql
#    environment:
#      PMA_HOST: some-mysql

  myphp:
    image: phpmyadmin/phpmyadmin
    ports:
      - 333:80
    depends_on:
      - some-mysql
    environment:
      PMA_HOST: some-mysql